# input device 3, output device 2, channel 2 for midi echo back messages...
# this is what is required for the USB-To-MIDI adapter I am using, and the Willams Allegro Keyboard
./pianomirror -i 3 -o 2 -c 2
